from __future__ import annotations

import argparse
import asyncio
import json
import os
from uuid import UUID

from app.core.config import get_settings
from app.core.real_company_acceptance import evaluate_real_company_acceptance
from app.db import create_database_engine


def _parse_job_ids(raw: str) -> list[UUID]:
    values: list[UUID] = []
    for item in raw.split(","):
        cleaned = item.strip()
        if cleaned:
            values.append(UUID(cleaned))
    return list(dict.fromkeys(values))


async def _run(job_ids: list[UUID], min_securities: int, min_sectors: int) -> dict[str, object]:
    settings = get_settings()
    if not settings.database_url:
        raise RuntimeError("DATABASE_URL must be configured")
    engine = create_database_engine(settings.database_url)
    try:
        return (
            await evaluate_real_company_acceptance(
                engine,
                job_ids,
                min_distinct_securities=min_securities,
                min_distinct_sectors=min_sectors,
            )
        ).as_dict()
    finally:
        await engine.dispose()


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Validate representative completed research against persisted real securities, reports, "
            "Agent 15/16 runs and source-linked claim evidence. No research or acceptance fixtures "
            "are generated by this command."
        )
    )
    parser.add_argument(
        "--job-ids",
        default=os.getenv("REAL_COMPANY_ACCEPTANCE_JOB_IDS", ""),
        help="Comma-separated completed real research job UUIDs; defaults to REAL_COMPANY_ACCEPTANCE_JOB_IDS.",
    )
    parser.add_argument("--min-securities", type=int, default=5)
    parser.add_argument("--min-sectors", type=int, default=4)
    args = parser.parse_args()
    if not 1 <= args.min_securities <= 20:
        parser.error("--min-securities must be between 1 and 20")
    if not 1 <= args.min_sectors <= args.min_securities:
        parser.error("--min-sectors must be between 1 and --min-securities")
    try:
        job_ids = _parse_job_ids(args.job_ids)
        payload = asyncio.run(_run(job_ids, args.min_securities, args.min_sectors))
    except (RuntimeError, ValueError) as exc:
        print(json.dumps({"ready": False, "errors": [str(exc)]}, indent=2, sort_keys=True))
        return 2
    print(json.dumps(payload, indent=2, sort_keys=True, default=str))
    return 0 if payload.get("ready") is True else 1


if __name__ == "__main__":
    raise SystemExit(main())
